spring:
  datasource:
    url: jdbc:mysql://db-lab-iot.c19mi8lie4w7.us-east-1.rds.amazonaws.com/lab_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: den
    password: Moiro123!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    # Show or not log for each sql query
    show-sql: true
    hibernate:
      # Hibernate ddl auto (validate, create, create-drop, update)
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  mvc:  # the fix for swagger
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8080
